# Generated by Django 3.1.4 on 2021-01-12 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='footer',
            field=models.CharField(default=django.utils.timezone.now, max_length=191),
            preserve_default=False,
        ),
    ]
