# Generated by Django 3.1.4 on 2021-01-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_posts_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='footer',
        ),
    ]
