# Generated by Django 3.1.4 on 2021-01-19 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
