# Generated by Django 3.1.4 on 2021-01-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20210119_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile',
        ),
    ]
