# Generated by Django 3.1.4 on 2021-02-03 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_remove_posts_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=191)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.posts')),
            ],
        ),
    ]
