# Generated by Django 3.1.4 on 2021-02-03 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
