# Generated by Django 3.1.4 on 2021-02-03 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_reply_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
