# Generated by Django 3.1.4 on 2021-02-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_auto_20210202_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
